language: python
python:
  - "3.8-dev"  # 3.8 development branch
install:
  - pip install -r requirements.txt
  - pip install opencv-python
  - pip install schedule
# command to run tests
script:
  - pytest
